# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"M\n\x14\x44\x65queueOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\norder_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\"\x15\n\x13\x44\x65queueOrderRequest\"<\n\x14\x45nqueueOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\nis_success\x18\x02 \x01(\x08\"^\n\x13\x45nqueueOrderRequest\x12\x10\n\x08priority\x18\x01 \x01(\x05\x12\x10\n\x08order_id\x18\x02 \x01(\x05\x12\x12\n\norder_type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t2\xbd\x01\n\x11OrderQueueService\x12S\n\x0c\x45nqueueOrder\x12 .order_queue.EnqueueOrderRequest\x1a!.order_queue.EnqueueOrderResponse\x12S\n\x0c\x44\x65queueOrder\x12 .order_queue.DequeueOrderRequest\x1a!.order_queue.DequeueOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEQUEUEORDERRESPONSE']._serialized_start=34
  _globals['_DEQUEUEORDERRESPONSE']._serialized_end=111
  _globals['_DEQUEUEORDERREQUEST']._serialized_start=113
  _globals['_DEQUEUEORDERREQUEST']._serialized_end=134
  _globals['_ENQUEUEORDERRESPONSE']._serialized_start=136
  _globals['_ENQUEUEORDERRESPONSE']._serialized_end=196
  _globals['_ENQUEUEORDERREQUEST']._serialized_start=198
  _globals['_ENQUEUEORDERREQUEST']._serialized_end=292
  _globals['_ORDERQUEUESERVICE']._serialized_start=295
  _globals['_ORDERQUEUESERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
