# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"<\n\x14\x45nqueueOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\nis_success\x18\x02 \x01(\x08\"L\n\x13\x45nqueueOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\norder_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t2h\n\x11OrderQueueService\x12S\n\x0c\x45nqueueOrder\x12 .order_queue.EnqueueOrderRequest\x1a!.order_queue.EnqueueOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENQUEUEORDERRESPONSE']._serialized_start=34
  _globals['_ENQUEUEORDERRESPONSE']._serialized_end=94
  _globals['_ENQUEUEORDERREQUEST']._serialized_start=96
  _globals['_ENQUEUEORDERREQUEST']._serialized_end=172
  _globals['_ORDERQUEUESERVICE']._serialized_start=174
  _globals['_ORDERQUEUESERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
