# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder.executor\"\x12\n\x10PassTokenRequest\"\x13\n\x11PassTokenResponse\"\x16\n\x14GetStateTokenRequest\"&\n\x15GetStateTokenResponse\x12\r\n\x05state\x18\x01 \x01(\t2\xca\x01\n\x14OrderExecutorService\x12R\n\tPassToken\x12 .order.executor.PassTokenRequest\x1a!.order.executor.PassTokenResponse\"\x00\x12^\n\rGetStateToken\x12$.order.executor.GetStateTokenRequest\x1a%.order.executor.GetStateTokenResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PASSTOKENREQUEST']._serialized_start=40
  _globals['_PASSTOKENREQUEST']._serialized_end=58
  _globals['_PASSTOKENRESPONSE']._serialized_start=60
  _globals['_PASSTOKENRESPONSE']._serialized_end=79
  _globals['_GETSTATETOKENREQUEST']._serialized_start=81
  _globals['_GETSTATETOKENREQUEST']._serialized_end=103
  _globals['_GETSTATETOKENRESPONSE']._serialized_start=105
  _globals['_GETSTATETOKENRESPONSE']._serialized_end=143
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=146
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=348
# @@protoc_insertion_point(module_scope)
