{
 "title": "Book store",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Order queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "order_queue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "6ac58a79", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "checkout" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Checkout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (state) (increase(checkout_counter_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}