# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\",\n\x16\x45xecutePaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\x05\"I\n\x15\x45xecutePaymentRequest\x12\x30\n\x0fpayment_details\x18\x01 \x01(\x0b\x32\x17.payment.PaymentDetails\"F\n\x0ePaymentDetails\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t2c\n\x0ePaymentService\x12Q\n\x0e\x45xecutePayment\x12\x1e.payment.ExecutePaymentRequest\x1a\x1f.payment.ExecutePaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTEPAYMENTRESPONSE']._serialized_start=26
  _globals['_EXECUTEPAYMENTRESPONSE']._serialized_end=70
  _globals['_EXECUTEPAYMENTREQUEST']._serialized_start=72
  _globals['_EXECUTEPAYMENTREQUEST']._serialized_end=145
  _globals['_PAYMENTDETAILS']._serialized_start=147
  _globals['_PAYMENTDETAILS']._serialized_end=217
  _globals['_PAYMENTSERVICE']._serialized_start=219
  _globals['_PAYMENTSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
